routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// AUTH 

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');

Route::post('login', 'Auth\LoginController@login');

Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/', 'HomeController@index')->name('home');
Route::get('/export-winner', 'HomeController@exportExcel')->name('home.export');

Route::group(['prefix' => 'contents', 'as' => 'random.'], function() {
    Route::get('/name', 'RandomNameController@index')->name('name');
    Route::get('/name-roulette', 'RandomNameController@roulette')->name('name-roulette');
    Route::post('/name/{id}', 'RandomNameController@onDecision')->name('name.choose');
    Route::get('/lottery-table', 'RandomLotteryController@index')->name('lottery-table');
    Route::post('/lottery-table/{id}', 'RandomLotteryController@onDecisionPrize')->name('lottery-table.choose');
    Route::get('/lottery-pizza', 'RandomLotteryPizzaController@index')->name('lottery-pizza');
    Route::post('/lottery-pizza/{id}', 'RandomLotteryPizzaController@onDecisionPrize')->name('lottery-pizza.choose');
});

Route::group(['prefix' => 'lists', 'as' => 'lists.'], function() {
    Route::get('/participants', 'ParticipantsController@index')->name('participants');
    Route::post('/participants', 'ParticipantsController@store')->name('participants.post');
    Route::post('/participants/import-excel', 'ParticipantsController@importExcel')->name('participants.import-excel');
    Route::get('/prizes', 'PrizesController@index')->name('prizes');
    Route::post('/prizes', 'PrizesController@store')->name('prizes.post');
    Route::post('/prizes/import-excel', 'PrizesController@importExcel')->name('prizes.import-excel');
});

Route::get('/settings/user', 'UserSettingController@index')->name('settings.user');
Route::post('/settings/user', 'UserSettingController@store')->name('settings.user.store');
Route::post('/settings/user/{id}', 'UserSettingController@update')->name('settings.user.update');
Route::delete('/settings/user/{id}/delete', 'UserSettingController@destroy')->name('settings.user.delete');

resources/views/contents/random_lottery.blade.php
@extends('layouts.app')

@section('title')
    Kocok Undian Tabel
@endsection

@section('section')
<section id="app">
            <div class="content-wrapper">
                <div class="container-fluid">
                    <div class="page-header">
                        <h2>Kocok Undian Tabel</h2>
                        <h5>Undian atas nama: {{ $participants->name }}</h5>
                    </div>
                    <div class="row">
                        <div class="col-lg-3 col-md-12 col-sm-12 col-xs-12" v-for="(data, index) in dataPrizes" :key="data.id">
                            <div class="card">
                                <div :class="idActive == data.id ? 'card--active' : data.is_taken != null ? 'card--active-green' : ''" class="body" v-if="data.is_taken != null">
                                    <img :src="data.file != null ? '{{ asset('storage') }}/' + data.file : '{{ asset('images/widget/3.jpg') }}'" alt="Random Prize" style="width: 100%; height: 125px;">
                                </div>
                                <div :class="idActive == data.id ? 'card--active' : ''" class="body has__center" style="width: 100%; height: 165px;" v-else>
                                    <img :src="data.file != null ? '{{ asset('storage') }}/' + data.file : '{{ asset('images/widget/3.jpg') }}'" alt="Random Prize" style="width: 100%; height: 125px;">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 has__center--horizontal">
                            <button class="btn btn-primary waves-effect text-uppercase m-t-15 btn__submit" @click="onClick" :disabled="loading ? true : false">
                                <div v-if="!loading">Kocok Undian</div>
                                    <div class="preloader icon__preloader" v-else>
                                            <div class="spinner-layer spinner-default">
                                                <div class="circle-clipper fl-left">
                                            <div class="circle"></div>
                                        </div>
                                        <div class="circle-clipper fl-right">
                                            <div class="circle"></div>
                                        </div>
                                    </div>
                                </div>
                            </button>
                            <button type="button" class="btn btn-default btn-outline waves-effect m-t-15 m-l-15 btn__submit" @click="stopRandom">Selesai</button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- MODAL ADD NEW -->
            <div class="modal fade" id="newChoosen" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">x</span></button>
                            <h4 class="modal-title" id="myModalLabel">Selamat {{ $participants->name }}!</h4>
                        </div>
                        <div class="modal-body">
                            Selamat {{ $participants->name }} Mendapatkan @{{ choosenPrize.name }}!!
                        </div>
                        <div class="modal-footer">
                            <form :action="onDecision" method="POST" enctype="multipart/form-data" style="display:contents;">
                            @csrf
                                <input type="hidden" name="is_taken" value="">
                                <button type="submit" class="btn btn-default">Batal</button>
                            </form>
                            <form :action="onDecision" method="POST" enctype="multipart/form-data" style="display:contents;">
                            @csrf
                                <input type="hidden" name="is_taken" value="1">
                                <button type="submit" class="btn btn-primary">Lanjut</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!-- END MODAL ADD NEW -->
        </section>
@endsection

@section('script')
    <script>
        Vue.config.devtools = true;
        var app = new Vue({
            el: '#app',
            data: {
                dataPrizes: [],
                namePrize: "",
                choosenPrize: {},
                loading: false,
                onDecision: "",
                idActive: null,
                intervalAnimation: null,
                timeoutRandom: null
            },
            mounted() {
                this.dataPrizes = @json($prizes);
            },
            methods: {
                stopRandom() {
                    clearTimeout(this.timeoutRandom);
                    this.namePrize = "";
                    this.nameParticipants = "";
                    let tmpIsTaken = this.dataPrizes.filter(x => x.is_taken == null);
                    let tmpChoosen = Math.floor(Math.random() * tmpIsTaken.length);
                    let tmpFind = this.dataPrizes.find(x => x.id == tmpIsTaken[tmpChoosen].id);
                    let tmpIndexFind = this.dataPrizes.indexOf(tmpFind);
                    this.choosenPrize = this.dataPrizes[tmpIndexFind];
                    this.namePrizes = this.dataPrizes[tmpIndexFind].name;
                    this.dataPrizes[tmpIndexFind].is_taken = 1;
                    this.loading = false;
                    this.idActive = this.dataPrizes[tmpIndexFind].id;
                    clearInterval(this.intervalAnimation);
                    // PLACEHOLDER
                    let urlAgree = '{{ route("random.lottery-table.choose", ":id") }}';
                    urlAgree = urlAgree.replace(':id', this.choosenPrize.id);
                    this.onDecision = urlAgree;
                    $('#newChoosen').modal({
                        show: 'true',
                        backdrop: 'static', 
                        keyboard: false
                    });
                },
                onClick() {
                    this.loading = true;
                    this.namePrize = "";
                    this.nameParticipants = "";
                    this.intervalAnimation = setInterval(() => {
                        let tmpChoosen = Math.floor(Math.random() * this.dataPrizes.length);
                        let tmpFind = this.dataPrizes.find(x => x.id == this.dataPrizes[tmpChoosen].id);
                        let tmpIndexFind = this.dataPrizes.indexOf(tmpFind);
                        this.idActive = this.dataPrizes[tmpChoosen].id;
                    }, 16);
                    this.timeoutRandom = setTimeout(() => {
                        let tmpChoosen = Math.floor(Math.random() * this.dataPrizes.length);
                        let tmpFind = this.dataPrizes.find(x => x.id == this.dataPrizes[tmpChoosen].id);
                        let tmpIndexFind = this.dataPrizes.indexOf(tmpFind);
                        this.choosenPrize = this.dataPrizes[tmpChoosen];
                        this.namePrizes = this.dataPrizes[tmpChoosen].name;
                        this.dataPrizes[tmpChoosen].is_taken = 1;
                        this.loading = false;
                        this.idActive = this.dataPrizes[tmpChoosen].id;
                        clearInterval(this.intervalAnimation);
                        // PLACEHOLDER
                        let urlAgree = '{{ route("random.lottery-table.choose", ":id") }}';
                        urlAgree = urlAgree.replace(':id', this.choosenPrize.id);
                        this.onDecision = urlAgree;
                        $('#newChoosen').modal({
                            show: 'true',
                            backdrop: 'static', 
                            keyboard: false
                        });
                    }, 10000);
                }
            }
        })
    </script>
@endsection

resources/views/contents/random_lottery_pizza.blade.php
@extends('layouts.app')

@section('title')
    Kocok Undian Pizza
@endsection

@section('section')
<section id="app">
            <div class="content-wrapper">
                <div class="container-fluid">
                    <div class="page-header">
                        <h2>Kocok Undian Roulette</h2>
                        <h5>Undian atas nama: {{ $participants->name }}</h5>
                    </div>
                    <div class="row clearfix">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 has__center">
                            <canvas id="canvas" width="500" height="500"></canvas>
                        </div>
                        <div class="col-lg-12 has__center m-b-20">
                            <button class="btn btn-primary waves-effect text-uppercase m-t-15 btn__submit" @click="spin" :disabled="loading ? true : false">
                                <div v-if="!loading">Kocok Undian</div>
                                    <div class="preloader icon__preloader" v-else>
                                            <div class="spinner-layer spinner-default">
                                                <div class="circle-clipper fl-left">
                                            <div class="circle"></div>
                                        </div>
                                        <div class="circle-clipper fl-right">
                                            <div class="circle"></div>
                                        </div>
                                    </div>
                                </div>
                            </button>
                            <button type="button" class="btn btn-default btn-outline waves-effect m-t-15 m-l-15 btn__submit" @click="stopSpin">Selesai</button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- MODAL ADD NEW -->
            <div class="modal fade" id="newChoosen" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">x</span></button>
                            <h4 class="modal-title" id="myModalLabel">Selamat {{ $participants->name }}!</h4>
                        </div>
                        <div class="modal-body">
                            Selamat {{ $participants->name }} Mendapatkan @{{ choosenPrize.name }}!!
                        </div>
                        <div class="modal-footer">
                            <form :action="onDecision" method="POST" enctype="multipart/form-data" style="display:contents;">
                            @csrf
                                <input type="hidden" name="is_taken" value="">
                                <button type="submit" class="btn btn-default">Batal</button>
                            </form>
                            <form :action="onDecision" method="POST" enctype="multipart/form-data" style="display:contents;">
                            @csrf
                                <input type="hidden" name="is_taken" value="1">
                                <button type="submit" class="btn btn-primary">Lanjut</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!-- END MODAL ADD NEW -->
        </section>
@endsection

@section('script')
<script>
Vue.config.devtools = true;
var app = new Vue ({
    el: '#app',
    data: {
        dataPrizes: [],
        namePrize: "",
        choosenPrize: {},
        onDecision: "",
        loading: false
    },
    mounted(){
        this.dataPrizes = @json($prizes);
    },
    methods: {
        spin() {
            this.namePrize = "";
            this.nameParticipants = "";
            this.loading = true;
            spinAngleStart = Math.random() * 10 + 10;
            spinTime = 0;
            spinTimeTotal = Math.random() * 3 + 4 * 1000;
            rotateWheel();
        },
        stopSpin() {
            stopRotateWheel();
            return;
            var spinAngle = spinAngleStart - easeOut(spinTime, 0, spinAngleStart, spinTimeTotal);
            startAngle += (spinAngle * Math.PI / 180);
            drawRouletteWheel();
            spinTimeout = setTimeout('rotateWheel()', 5);
        }
    }
})
var startAngle = 0;
var arc = Math.PI / (app.dataPrizes.length / 2);
var spinTimeout = null;

var spinArcStart = 10;
var spinTime = 0;
var spinTimeTotal = 0;

var ctx;

function byte2Hex(n) {
  var nybHexString = "0123456789ABCDEF";
  return String(nybHexString.substr((n >> 4) & 0x0F,1)) + nybHexString.substr(n & 0x0F,1);
}

function RGB2Color(r,g,b) {
	return '#' + byte2Hex(r) + byte2Hex(g) + byte2Hex(b);
}

function getColor(item, maxitem) {
  var phase = 0;
  var center = 128;
  var width = 127;
  var frequency = Math.PI*2/maxitem;
  
  red   = Math.sin(frequency*item+2+phase) * width + center;
  green = Math.sin(frequency*item+0+phase) * width + center;
  blue  = Math.sin(frequency*item+4+phase) * width + center;
  
  return RGB2Color(red,green,blue);
}

function drawRouletteWheel() {
  var canvas = document.getElementById("canvas");
  if (canvas.getContext) {
    var outsideRadius = 200;
    var textRadius = 160;
    var insideRadius = 125;

    ctx = canvas.getContext("2d");
    ctx.clearRect(0,0,500,500);

    ctx.strokeStyle = "black";
    ctx.lineWidth = 2;

    ctx.font = 'bold 12px Helvetica, Arial';

    for(var i = 0; i < app.dataPrizes.length; i++) {
      var angle = startAngle + i * arc;
      //ctx.fillStyle = colors[i];
      ctx.fillStyle = getColor(i, app.dataPrizes.length);

      ctx.beginPath();
      ctx.arc(250, 250, outsideRadius, angle, angle + arc, false);
      ctx.arc(250, 250, insideRadius, angle + arc, angle, true);
      ctx.stroke();
      ctx.fill();

      ctx.save();
      ctx.shadowOffsetX = -1;
      ctx.shadowOffsetY = -1;
      ctx.shadowBlur    = 0;
      ctx.shadowColor   = "rgb(220,220,220)";
      ctx.fillStyle = "black";
      ctx.translate(250 + Math.cos(angle + arc / 2) * textRadius, 
                    250 + Math.sin(angle + arc / 2) * textRadius);
      ctx.rotate(angle + arc / 2 + Math.PI / 2);
      var text = app.dataPrizes[i].name;
      ctx.fillText(text, -ctx.measureText(text).width / 2, 0);
      ctx.restore();
    } 

    //Arrow
    ctx.fillStyle = "black";
    ctx.beginPath();
    ctx.moveTo(250 - 4, 250 - (outsideRadius + 5));
    ctx.lineTo(250 + 4, 250 - (outsideRadius + 5));
    ctx.lineTo(250 + 4, 250 - (outsideRadius - 5));
    ctx.lineTo(250 + 9, 250 - (outsideRadius - 5));
    ctx.lineTo(250 + 0, 250 - (outsideRadius - 13));
    ctx.lineTo(250 - 9, 250 - (outsideRadius - 5));
    ctx.lineTo(250 - 4, 250 - (outsideRadius - 5));
    ctx.lineTo(250 - 4, 250 - (outsideRadius + 5));
    ctx.fill();
  }
}

function rotateWheel() {
  spinTime += 30;
  if(spinTime >= spinTimeTotal) {
    stopRotateWheel();
    return;
  }
  var spinAngle = spinAngleStart - easeOut(spinTime, 0, spinAngleStart, spinTimeTotal);
  startAngle += (spinAngle * Math.PI / 180);
  drawRouletteWheel();
  spinTimeout = setTimeout('rotateWheel()', 30);
}

function stopRotateWheel() {
  clearTimeout(spinTimeout);
  var degrees = startAngle * 180 / Math.PI + 90;
  var arcd = arc * 180 / Math.PI;
  var index = Math.floor((360 - degrees % 360) / arcd);
  ctx.save();
  ctx.font = 'bold 30px Helvetica, Arial';
  var text = app.dataPrizes[index].name;
  app.choosenPrize = app.dataPrizes[index];
  app.namePrizes = app.dataPrizes[index].name;
  app.loading = false;
  let urlAgree = '{{ route("random.lottery-pizza.choose", ":id") }}';
  urlAgree = urlAgree.replace(':id', app.choosenPrize.id);
  app.onDecision = urlAgree;
  $('#newChoosen').modal({
    show: 'true',
    backdrop: 'static', 
    keyboard: false
  });
  ctx.fillText(text, 250 - ctx.measureText(text).width / 2, 250 + 10);
  ctx.restore();
}

function easeOut(t, b, c, d) {
  var ts = (t/=d)*t;
  var tc = ts*t;
  return b+c*(tc + -3*ts + 3*t);
}

drawRouletteWheel();
</script>
@endsection

resources/views/contents/random_name.blade.php
@extends('layouts.app')

@section('title')
    Acak Nama
@endsection

@section('section')
<section id="app">
            <div class="content-wrapper">
                <div class="container-fluid">
                    <div class="page-header">
                        <h2>Acak Nama</h2>
                    </div>
                    @if(\Session::has('success'))
                    <div class="col-md-12">
                        <div class="alert dark alert-icon bg-green alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <i class="material-icons">info_outline</i>
                            {{\Session::get('success')}}
                        </div>
                    </div>
                    @endif
                    @if(\Session::has('warning'))
                    <div class="col-md-12">
                        <div class="alert dark alert-icon alert-danger alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <i class="material-icons">info_outline</i>
                            {{\Session::get('warning')}}
                        </div>
                    </div>
                    @endif
                    <div class="row clearfix">
                        <div class="col-lg-3"></div>
                        <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
                            <div class="card">
                                <div class="body" style="padding: 65px 50px;">
                                    <!-- <form> -->
                                        <div class="form-group m-b-10">
                                        <label>Nama Peserta</label>
                                            <input type="text" class="form-control" placeholder="Nama Peserta" name="name" v-model="name" disabled />
                                        </div>
                                        <div>
                                            <button class="btn btn-primary btn-outline waves-effect btn-block text-uppercase m-t-15" @click="onClick" :disabled="loading ? true : false">
                                            <div v-if="!loading">Acak Nama</div>
                                            <div class="preloader icon__preloader" v-else>
                                                <div class="spinner-layer spinner-default">
                                                    <div class="circle-clipper fl-left">
                                                        <div class="circle"></div>
                                                    </div>
                                                    <div class="circle-clipper fl-right">
                                                        <div class="circle"></div>
                                                    </div>
                                                </div>
                                            </div>
                                            </button>
                                            <button type="button" class="btn btn-default btn-outline waves-effect btn-block" style="margin-top: 20px !important;" @click="stopRandom">Selesai</button>
                                        </div>
                                    <!-- </form> -->
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3"></div>
                    </div>
                </div>
            </div>
            <!-- MODAL ADD NEW -->
            <div class="modal fade" id="newChoosen" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">x</span></button>
                            <h4 class="modal-title" id="myModalLabel">Selamat @{{ name }}!</h4>
                        </div>
                        <div class="modal-body">
                            Silahkan @{{ name }} Memilih Hadiah Sebagai Berikut!!
                        </div>
                        <div class="modal-footer">
                            <form :action="onDecision" method="POST" enctype="multipart/form-data" style="display:contents;">
                            @csrf
                                <input type="hidden" name="is_choosen" value="0">
                                <button type="submit" class="btn btn-default">Batal</button>
                            </form>
                            <form :action="onDecision" method="POST" enctype="multipart/form-data" style="display:contents;">
                            @csrf
                                <input type="hidden" name="is_choosen" value="1">
                                <button type="submit" class="btn btn-primary">Lanjut</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!-- END MODAL ADD NEW -->
        </section>
@endsection

@section('script')
    <script>
        Vue.config.devtools = true;
        var app = new Vue({
            el: '#app',
            data: {
                dataName: [],
                choosenData: {},
                name: "",
                loading: false,
                onDecision: "",
                timeoutRandom: null
            },
            mounted() {
                this.dataName = @json($participants);
            },
            methods: {
                stopRandom() {
                    clearTimeout(this.timeoutRandom);
                    this.loading = true;
                    this.name = "";
                    let tmpChoosen = Math.floor(Math.random() * this.dataName.length);
                        this.choosenData = this.dataName[tmpChoosen];
                        this.name = this.dataName[tmpChoosen].name;
                        this.loading = false;
                        // AGREE PLACEHOLDER ROUTE
                        let urlAgree = '{{ route("random.name.choose", ":id") }}';
                        urlAgree = urlAgree.replace(':id', this.choosenData.id);
                        this.onDecision = urlAgree;
                        $('#newChoosen').modal({
                            show: 'true',
                            backdrop: 'static', 
                            keyboard: false
                        });
                },

                onClick() {
                    this.loading = true;
                    this.name = "";
                    this.randomName = setTimeout(() => {
                        let tmpChoosen = Math.floor(Math.random() * this.dataName.length);
                        this.choosenData = this.dataName[tmpChoosen];
                        this.name = this.dataName[tmpChoosen].name;
                        this.loading = false;
                        // AGREE PLACEHOLDER ROUTE
                        let urlAgree = '{{ route("random.name.choose", ":id") }}';
                        urlAgree = urlAgree.replace(':id', this.choosenData.id);
                        this.onDecision = urlAgree;
                        $('#newChoosen').modal({
                            show: 'true',
                            backdrop: 'static', 
                            keyboard: false
                        });
                    }, 10000);
                }
            }
        });
    </script>
@endsection