routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// AUTH 

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');

Route::post('login', 'Auth\LoginController@login');

Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/', 'HomeController@index')->name('home');
Route::get('/export-winner', 'HomeController@exportExcel')->name('home.export');

Route::group(['prefix' => 'contents', 'as' => 'random.'], function() {
    Route::get('/name', 'RandomNameController@index')->name('name');
    Route::get('/name-roulette', 'RandomNameController@roulette')->name('name-roulette');
    Route::post('/name/{id}', 'RandomNameController@onDecision')->name('name.choose');
    Route::get('/lottery-table', 'RandomLotteryController@index')->name('lottery-table');
    Route::post('/lottery-table/{id}', 'RandomLotteryController@onDecisionPrize')->name('lottery-table.choose');
    Route::get('/lottery-pizza', 'RandomLotteryPizzaController@index')->name('lottery-pizza');
    Route::post('/lottery-pizza/{id}', 'RandomLotteryPizzaController@onDecisionPrize')->name('lottery-pizza.choose');
});

Route::group(['prefix' => 'lists', 'as' => 'lists.'], function() {
    Route::get('/participants', 'ParticipantsController@index')->name('participants');
    Route::post('/participants', 'ParticipantsController@store')->name('participants.post');
    Route::post('/participants/import-excel', 'ParticipantsController@importExcel')->name('participants.import-excel');
    Route::get('/prizes', 'PrizesController@index')->name('prizes');
    Route::post('/prizes', 'PrizesController@store')->name('prizes.post');
    Route::post('/prizes/import-excel', 'PrizesController@importExcel')->name('prizes.import-excel');
});

Route::get('/settings/user', 'UserSettingController@index')->name('settings.user');
Route::post('/settings/user', 'UserSettingController@store')->name('settings.user.store');
Route::post('/settings/user/{id}', 'UserSettingController@update')->name('settings.user.update');
Route::delete('/settings/user/{id}/delete', 'UserSettingController@destroy')->name('settings.user.delete');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>Gathering Prize | @yield('title')</title>
    <!-- Favicon-->
    <link rel="icon" href="{{asset('favicon.png')}}" type="image/x-icon">

    <!--REQUIRED PLUGIN CSS-->
    <link href="{{asset('plugins/font-awesome/css/font-awesome.min.css')}}" rel="stylesheet">
    <link href="{{asset('plugins/bootstrap/css/bootstrap.css')}}" rel="stylesheet">
    <link href="{{asset('plugins/node-waves/waves.css')}}" rel="stylesheet" />
    <link href="{{asset('plugins/animate-css/animate.css')}}" rel="stylesheet" />
    <link href="{{asset('plugins/spinkit/spinkit.css')}}" rel="stylesheet">

    <!-- THIS PAGE CSS -->
    @yield('styles')

    <!--REQUIRED THEME CSS -->
    <link href="{{asset('css/style.css')}}" rel="stylesheet">
    <link rel="stylesheet" href="{{asset('css/app.css')}}">
    <link href="{{asset('css/layout.css')}}" rel="stylesheet">
    <link href="{{asset('css/themes/main_theme.css')}}" rel="stylesheet" />
</head>

<body class="theme-indigo light layout-fixed">
<div class="wrapper">
    <!-- top navbar-->
    <header class="topnavbar-wrapper">
        <nav role="navigation" class="navbar topnavbar">
            <!-- START navbar header-->
            <div class="navbar-header">
                <a href="{{ url('/') }}" class="navbar-brand has__center--horizontal" style="position: relative; flex-direction: column;">
                    <div class="brand-logo" style="position: absolute;">
                        <img src="{{asset('images/logo.png')}}" alt="Admin Logo" class="img-responsive">
                    </div>
                    <div class="brand-logo-collapsed" style="position:absolute;">
                       <img src="{{asset('images/logo-single.png')}}" alt="Admin Logo" class="img-responsive">
                    </div>
                </a>
            </div>
            <!-- END navbar header-->
            <!-- START Nav wrapper-->
            <div class="nav-wrapper">
                <!-- START Left navbar-->
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#" data-trigger-resize="" data-toggle-state="aside-collapsed" class="hidden-xs">
                            <em class="material-icons">menu</em>
                        </a>
                        <a href="#" data-toggle-state="aside-toggled" data-no-persist="true" class="visible-xs sidebar-toggle">
                            <em class="material-icons">menu</em>
                        </a>
                    </li>
                </ul>
                <!-- END Left navbar-->
                <!-- START Right Navbar-->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Task -->
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button">
                            <i class="material-icons">account_circle</i>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="{{ route('logout') }}"
                                    onclick="event.preventDefault();
                                    document.getElementById('logout-form').submit();">
                                    Log Out
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    {{ csrf_field() }}
                                </form>
                            </li>
                        </ul>
                    </li>
                    <!-- #END# Task -->
                </ul>
                <!-- #END# Right Navbar-->
            </div>
            <!-- #END# Nav wrapper-->
        </nav>
        <!-- END Top Navbar-->
    </header>
    <!-- sidebar-->
    @include('layouts.sidebar')

    <!-- Main section-->
        @yield('section')
    <!-- FOOTER-->
    <footer>
        <span>&copy; 2019 - Gathering Prize By <a href="https://axelandrian.me" target="_blank"><b class="col-blue">Axel Andrian</b></a></span>
    </footer>
</div>
    <!-- CORE PLUGIN JS -->
    <script src="{{asset('plugins/jquery/jquery.min.js')}}"></script>
    <script src="{{asset('js/vue.js')}}"></script>
    <script src="{{asset('plugins/bootstrap/js/bootstrap.js')}}"></script>
    <script src="{{asset('plugins/modernizr/modernizr.custom.js')}}"></script>
    <script src="{{asset('plugins/screenfull/dist/screenfull.js')}}"></script>
    <script src="{{asset('plugins/jQuery-Storage-API/jquery.storageapi.js')}}"></script>
    <script src="{{asset('plugins/jquery-slimscroll/jquery.slimscroll.js')}}"></script>
    <script src="{{asset('plugins/node-waves/waves.js')}}"></script>
    
    <!-- LAYOUT JS -->
    <script src="{{asset('js/demo.js')}}"></script>
    <script src="{{asset('js/layout.js')}}"></script>

    <!-- THIS PAGE LEVEL JS -->
    @yield('script')

</body>

</html>

resources/views/layouts/app_login.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    <link rel="icon" href="{{asset('favicon.png')}}" type="image/x-icon">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('titles')</title>

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">

    <!-- Bootstrap Core Css -->
    <link href="{{asset('plugins/bootstrap/css/bootstrap.css')}}" rel="stylesheet">

    <!-- Waves Effect Css -->
    <link href="{{asset('plugins/node-waves/waves.css')}}" rel="stylesheet" />

    <!-- Animation Css -->
    <link href="{{asset('plugins/animate-css/animate.css')}}" rel="stylesheet" />

    <!-- Custom Css -->
    <link href="{{asset('css/style.css')}}" rel="stylesheet">
    @yield('css')
</head>


    <body class="login-page">

        @yield('content')

        <!-- CORE PLUGIN JS -->
        <script src="{{asset('plugins/jquery/jquery.min.js')}}"></script>
        <script src="{{asset('plugins/bootstrap/js/bootstrap.js')}}"></script>
        <script src="{{asset('plugins/node-waves/waves.js')}}"></script>
        <script src="{{asset('plugins/jquery-slimscroll/jquery.slimscroll.js')}}"></script>

        <!--THIS PAGE LEVEL JS-->
        <script src="{{asset('plugins/jquery-validation/jquery.validate.js')}}"></script>
        <script src="{{asset('js/pages/examples/login.js')}}"></script>

        <!-- LAYOUT JS -->
        <script src="{{asset('js/demo.js')}}"></script>

        @yield('scripts')
    </body>
</html>

resources/views/layouts/sidebar.blade.php
    <aside class="aside">
        <!-- START Sidebar (left)-->
        <div class="aside-inner">
            <nav data-sidebar-anyclick-close="" class="sidebar">
                <!-- START sidebar nav-->
                <ul class="nav menu">
                    <!-- Iterates over all sidebar items-->
                    <li class="nav-heading ">
                        <span>MAIN NAVIGATION</span>
                    </li>
                    <li>
                        <a href="{{ route('home') }}" title="Dashboard">
                            <em class="material-icons">school</em>
                            <span>Dashboard</span>
                        </a>
                    </li>
                    <li>
                        <a href="{{ route('random.name') }}" title="Acak Nama">
                            <em class="material-icons">shuffle</em>
                            <span>Acak Nama</span>
                        </a>
                    </li>
                    <li>
                        <a href="{{ route('random.name-roulette') }}" title="Kocak Undian Pizza">
                            <em class="material-icons">local_pizza</em>
                            <span>Kocok Nama Roulette</span>
                        </a>
                    </li>
                    @if(session()->get('role') == 'superadmin' || session()->get('role') == 'admintabel')
                    <li>
                        <a href="{{ route('random.lottery-table') }}" title="Kocok Undian Tabel">
                            <em class="material-icons">table_chart</em>
                            <span>Kocok Undian Tabel</span>
                        </a>
                    </li>
                    @endif
                    @if(session()->get('role') == 'superadmin' || session()->get('role') == 'adminroulette')
                    <li>
                        <a href="{{ route('random.lottery-pizza') }}" title="Kocak Undian Pizza">
                            <em class="material-icons">local_pizza</em>
                            <span>Kocok Undian Roulette</span>
                        </a>
                    </li>
                    @endif
                    @if(session()->get('role') == 'superadmin')
                    <li>
                        <a href="#layout" title="Layouts" data-toggle="collapse" class="menu-toggle">
                            <em class="material-icons">list</em>
                            <span>Lists</span>
                        </a>
                        <ul id="layout" class="nav sidebar-subnav collapse">
                            <li class="sidebar-subnav-header">Lists</li>
                            <li>
                                <a href="{{ route('lists.participants') }}" title="List Peserta">
                                    <span>List Peserta</span>
                                </a>
                            </li>
                            <li>
                                <a href="{{ route('lists.prizes') }}" title="List Undian">
                                    <span>List Hadiah</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#setting" title="Kocak Undian Pizza" data-toggle="collapse" class="menu-toggle">
                            <em class="material-icons">settings_applications</em>
                            <span>Settings</span>
                        </a>
                        <ul id="setting" class="nav sidebar-subnav collapse">
                            <li class="sidebar-subnav-header">Settings</li>
                            <li>
                                <a href="{{ route('settings.user') }}" title="Manage Users">
                                    <span>Manage Users</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                    @endif
                </ul>
                <!-- END sidebar nav-->
            </nav>
        </div>
        <!-- #END# Sidebar (left)-->
    </aside>